### ISSUE TITLE
Github API post comment error: body is too long

### ISSUE THREAD

**Issue by lnjX** [cpp-linter/cpp-linter#89]
I'm encountering the following error:

```
Posting comment(s)
  ERROR:CPP Linter:response returned 422 from POST https://api.github.com/repos/qxmpp-project/qxmpp/commits/46f2f3dbc69270de2a82b0db37cc69422bb3c435/comments with message: {"message":"Validation Failed","errors":[{"resource":"CommitComment","code":"custom","field":"body","message":"body is too long (maximum is 65536 characters)"}],"documentation_url":"https://docs.github.com/rest/commits/comments#create-a-commit-comment"}
  Traceback (most recent call last):
    File "/home/runner/work/_actions/cpp-linter/cpp-linter-action/v2/venv/bin/cpp-linter", line 8, in <module>
      sys.exit(main())
    File "/home/runner/work/_actions/cpp-linter/cpp-linter-action/v2/venv/lib/python3.10/site-packages/cpp_linter/__init__.py", line 93, in main
      rest_api_client.post_feedback(
    File "/home/runner/work/_actions/cpp-linter/cpp-linter-action/v2/venv/lib/python3.10/site-packages/cpp_linter/rest_api/github_api.py", line 235, in post_feedback
      self.update_comment(comment, comments_url, no_lgtm, update_only, is_lgtm)
    File "/home/runner/work/_actions/cpp-linter/cpp-linter-action/v2/venv/lib/python3.10/site-packages/cpp_linter/rest_api/github_api.py", line 329, in update_comment
      self.api_request(url=comments_url, method=req_meth, data=payload)
    File "/home/runner/work/_actions/cpp-linter/cpp-linter-action/v2/venv/lib/python3.10/site-packages/cpp_linter/rest_api/github_api.py", line 130, in api_request
      response.raise_for_status()
    File "/home/runner/work/_actions/cpp-linter/cpp-linter-action/v2/venv/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
      raise HTTPError(http_error_msg, response=self)
  requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://api.github.com/repos/qxmpp-project/qxmpp/commits/46f2f3dbc69270de2a82b0db37cc69422bb3c435/comments
```

For example, see the following pipeline:
https://github.com/qxmpp-project/qxmpp/actions/runs/8272603618/job/22634759413#step:3:2201

**Comment by 2bndy5** [comment]
@lnjX Using [step-summary](https://cpp-linter.github.io/cpp-linter-action/#step-summary) will suite your needs a bit better.
```yml
      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        with:
          style: file
          version: 15
          files-changed-only: false
          step-summary: true
```

**Comment by lnjX** [comment]
Thanks for the hint and the PR. :)

Unfortunately I got a 403 Forbidden now:

```
Posting comment(s)
  ERROR:CPP Linter:response returned 403 from POST https://api.github.com/repos/qxmpp-project/qxmpp/issues/605/comments with message: {"message":"Resource not accessible by integration","documentation_url":"https://docs.github.com/rest/issues/comments#create-an-issue-comment"}
  Traceback (most recent call last):
    File "/home/runner/work/_actions/cpp-linter/cpp-linter-action/v2/venv/bin/cpp-linter", line 8, in <module>
      sys.exit(main())
    File "/home/runner/work/_actions/cpp-linter/cpp-linter-action/v2/venv/lib/python3.10/site-packages/cpp_linter/__init__.py", line 93, in main
      rest_api_client.post_feedback(
    File "/home/runner/work/_actions/cpp-linter/cpp-linter-action/v2/venv/lib/python3.10/site-packages/cpp_linter/rest_api/github_api.py", line 235, in post_feedback
      self.update_comment(comment, comments_url, no_lgtm, update_only, is_lgtm)
    File "/home/runner/work/_actions/cpp-linter/cpp-linter-action/v2/venv/lib/python3.10/site-packages/cpp_linter/rest_api/github_api.py", line 329, in update_comment
      self.api_request(url=comments_url, method=req_meth, data=payload)
    File "/home/runner/work/_actions/cpp-linter/cpp-linter-action/v2/venv/lib/python3.10/site-packages/cpp_linter/rest_api/github_api.py", line 130, in api_request
      response.raise_for_status()
    File "/home/runner/work/_actions/cpp-linter/cpp-linter-action/v2/venv/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
      raise HTTPError(http_error_msg, response=self)
  requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.github.com/repos/qxmpp-project/qxmpp/issues/605/comments
  Error: Process completed with exit code 1.
```

https://github.com/qxmpp-project/qxmpp/pull/605

**Comment by 2bndy5** [comment]
Looking at your repo's history, I don't think the thread-comment feature is very useful to you. If you're going to
1. analyze every line of every file (in a large repo) every time you submit changes
2. not address anything stated in the thread comment (or step-summary)

then simply turn off the [`thread-commment`](https://cpp-linter.github.io/cpp-linter-action/inputs-outputs/#thread-comments) feature (by removing it from the cpp-linter-action parameters or setting it to it's default value `false`)
